linters:
  presets:
    - bugs
    - error
    - unused
    - comment
    - format
    - importTw
    - metalinter
    - module
    - performance
    - sql
  disable:
    - wrapcheck
    - goerr113
    - depguard
    - tagalign
    - godot
